### ISSUE TITLE
REWRITE IT IN RUST

### ISSUE THREAD

**Issue by ErikMcClure** [Fundament-Software/feathergui#50]
rewrite the backends in rust because fuck C++ honestly

**Comment by faithanalog** [comment]
mood

**Comment by mintyfresh** [comment]
Don't fuck C++. You might make more of it.

**Comment by ErikMcClure** [comment]
We can't do this without a lot of "unsafe", because Rust really hates global state in OpenGL, which makes bindings difficult to use. Punting this until we have a rust expert with enough time to spend on dealing with the consequences of this.
